# Generated by Django 4.2.25 on 2025-11-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('party', 'Party'), ('birthday', 'Birthday Party'), ('corporate', 'Corporate Event'), ('charity', 'Charity Function')], max_length=20)),
                ('date', models.DateField()),
                ('guest_count', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='signup_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=225)),
            ],
        ),
    ]
