# Generated by Django 4.2.25 on 2025-11-13 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event2', '0002_delete_signup_detail_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('Credit/Debit Card', 'Credit/Debit Card'), ('UPI', 'UPI'), ('PayPal', 'PayPal')], max_length=30)),
                ('upi_app', models.CharField(blank=True, choices=[('GPay', 'GPay'), ('PhonePe', 'PhonePe'), ('Paytm', 'Paytm')], max_length=20, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
